### ISSUE TITLE
WebsocketNotConnectedException causing errors on entire server

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#191]
When a websocket loses connection without being marked as offline, big fat error happens causing all other clients that connect receive an error message because the server cannot send a message to this websocket:

    [2015-04-26 23:39:52,721]  INFO ClientWebSocket [WebsocketSelector21] (  ClientWebSocket.java: 44) - Sending to client: com.cardshifter.api.outgoing.ClientDisconnectedMessage@2abbd36a - [0, 0, 0, 42, 0, 0, 0, 10, 0, 100, 0, 105, 0, 115, 0, 99, 0, 111, 0, 110, 0, 110, 0, 101, 0, 99, 0, 116, 0, 0, 0, 5, 0, 90, 0, 111, 0, 109, 0, 105, 0, 115, 0, 0, 0, 1]
    [2015-04-26 23:39:52,721]  WARN  ServerWeb [WebsocketSelector21] (        ServerWeb.java: 87) - Connection error: org.java_websocket.WebSocketImpl@6c2fad21
    org.java_websocket.exceptions.WebsocketNotConnectedException
    	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
    	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
    	at com.cardshifter.server.clients.ClientWebSocket.onSendToClient(ClientWebSocket.java:45)
    	at com.cardshifter.api.ClientIO.sendToClient(ClientIO.java:27)
    	at com.cardshifter.core.game.ServerGame.lambda$send$115(ServerGame.java:95)
    	at com.cardshifter.core.game.ServerGame$$Lambda$210/1399698386.accept(Unknown Source)

Use if-check to make sure websocket is connected before sending message. And/Or catch exception(s)

**Comment by Zomis** [comment]
This is still an issue, and a very important one as well, as it completely screws up the server, which then needs to be restarted.
