### ISSUE TITLE
WebSocket connection close results in StackOverflowError

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#352]
I've been noticing this issue lately and has been particularly frustrating now that the web client runs with `npm` where every change it the client source code causes an app refresh, which then causes the error and requires restarting a game server to continue. 

I've copied a [full server log](http://pastebin.com/psrpZnVH) and below are the lines where the error occurs. 

_Note that for this log, my username was `pl0x`.

Trigger appears to start at lines 116-117:

    [2015-08-11 00:07:39,037]  INFO  ServerWeb [WebsocketSelector11] (        ServerWeb.java: 57) - Connection closed: org.java_websocket.WebSocketImpl@5be3dc07 code 1001 reason  remote true
    [2015-08-11 00:07:39,049]  INFO ClientWebSocket [WebsocketSelector11] (  ClientWebSocket.java: 47) - Manual close 6: pl0x @ /127.0.0.1:58852

And at that point it looks like it's going into an infinite back & forth of these two messages:

    [2015-08-11 00:07:39,051]  INFO     Server [WebsocketSelector11] (           Server.java:169) - Client disconnected: 6: pl0x @ /127.0.0.1:58852
    [2015-08-11 00:07:39,058]  INFO Log4jAdapter [WebsocketSelector11] (     Log4jAdapter.java: 16) - Send to pl0x: com.cardshifter.api.outgoing.ClientDisconnectedMessage@ca37f3

Then at line 1007 finally:

    Exception in thread "WebsocketSelector11" java.lang.StackOverflowError
        at java.lang.StringBuffer.setLength(StringBuffer.java:194)
        at org.apache.log4j.PatternLayout.format(PatternLayout.java:500)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.info(Category.java:666)
        at com.cardshifter.core.Log4jAdapter.info(Log4jAdapter.java:16)
        at com.cardshifter.api.ClientIO.sendToClient(ClientIO.java:26)
        at com.cardshifter.core.game.ServerGame.lambda$send$22(ServerGame.java:95)
        at com.cardshifter.core.game.ServerGame$$Lambda$100/344551577.accept(Unknown Source)
    ...

**Comment by danpantry** [comment]
Note that you can opt-out of the auto refresh by just going to `http;//localhost:8080` instead of `http://localhost:8080/webpack-dev-server`. This doesn't fix the issue obviously.

**Comment by Zomis** [comment]
I think this is entirely server-related. The issue is *probably* (without having looked at the code recently) that when the client has disconnected, the server sends this information to all clients (including the client itself), but when sending the info to the client it cannot do that because the socket is closed, so it tries to disconnect the client, and then informs all clients that the client has disconnected (including the client itself), but it cannot send the message to the client because the socket is closed...

Should be easy to fix, by doing things in a different order.

**Comment by Zomis** [comment]
The recursion loop seems to be this:

        at com.cardshifter.api.ClientIO.disconnected(ClientIO.java:57)
        at com.cardshifter.server.clients.ClientWebSocket.onSendToClient(ClientWebSocket.java:54)
        at com.cardshifter.api.ClientIO.sendToClient(ClientIO.java:27)
        at com.cardshifter.core.game.ServerGame.lambda$send$22(ServerGame.java:95)
        at com.cardshifter.core.game.ServerGame$$Lambda$100/344551577.accept(Unknown Source)
        ...
        at com.cardshifter.core.game.ServerGame.send(ServerGame.java:95)
        at com.cardshifter.server.model.Server.lambda$onDisconnected$3(Server.java:171)
        at com.cardshifter.server.model.Server$$Lambda$99/132060623.accept(Unknown Source)
        ...
        at com.cardshifter.server.model.Server.onDisconnected(Server.java:171)
        at com.cardshifter.api.ClientIO.disconnected(ClientIO.java:57)

**Comment by Zomis** [comment]
The issue occured when trying to send a [`ClientDisconnectedMessage`](https://github.com/Cardshifter/Cardshifter/blob/develop/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/ClientDisconnectedMessage.java) (which I didn't even remembered existed) to all the players in the game that was played.
