### ISSUE TITLE
Connecting with the HTML client crashes the server connection thread

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#353]
This happens _only when not_ using http://www.cardshifter.com/releases/cardshifter-0.6.1-SNAPSHOT-20150729-0036.zip as far as I can tell.

These are the versions I've tried:
- master
- develop
- 0.6 tag

These are the methods I've tried
- IDEA->Run
- `./gradlew dist && java -jar`

When a HTML client connects through WebSocket this is what is logged:
```
[2015-08-11 22:16:27,944]  INFO  ServerWeb [WebSocketWorker-11] (        ServerWeb.java: 46) - Connection opened: org.java_websocket.WebSocketImpl@2b09d1d7
[2015-08-11 22:16:27,944]  INFO     Server [WebSocketWorker-11] (           Server.java:158) - New client: 6:  @ /127.0.0.1:45551
[2015-08-11 22:16:27,958]  INFO  ServerWeb [WebSocketWorker-11] (        ServerWeb.java: 66) - Connection message from: org.java_websocket.WebSocketImpl@2b09d1d7: {"username":"jacwah","command":"login"}
[2015-08-11 22:16:27,959]  WARN  ServerWeb [WebSocketWorker-11] (        ServerWeb.java: 84) - Connection error: org.java_websocket.WebSocketImpl@2b09d1d7
java.lang.ArrayIndexOutOfBoundsException: 39
	at com.cardshifter.server.clients.Base64Utils.fromBase64(Base64Utils.java:92)
	at com.cardshifter.server.model.ServerWeb$InnerServer.onMessage(ServerWeb.java:73)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:469)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:657)
```
The WebSocket server tries to Base64 decode the message - which doesn't make sense since it isn't Base64 encoded. The code in that snapshot that works must be completely different.

**Comment by SirPython** [comment]
I did a little of [bisect](file:///C:/Program%20Files%20(x86)/Git/doc/git/html/git-bisect.html)ing and was brought back to [this commit](https://github.com/Cardshifter/HTML-Client/commit/6b885c8914698561a961fabb225980071fcb6664).

I can't see how this could've possibly broken the code: in fact, this commit was fixing a bug where the `.command` attribute of the message was not being sent.

However, that confuses me even more: how did the previous commit work when the `.command` attribute was not being sent?

**Comment by SirPython** [comment]
Aha! I was wrong about the previous commit working; the client would navigate to the lobby page regardless of what the server said.

To test, I opened up a local server and tried connecting to that instead; there was an error for there being no `.command`.

I will now try to bisect the project again, now knowing that I should test each commit on two servers: dwarftowers and a local host server.

**Comment by SirPython** [comment]
Through slightly off testing and extreme confusion, I have come to the conclusion that it was never possible for the HTML-Client to connect to any server other than a local one.

**Comment by Zomis** [comment]
> This happens only when not using (the latest snapshot)

That, is exactly why there is snapshots.

Use an updated version of both the client and the server and everything is fine. I don't see any issue here.

**Comment by jacwah** [comment]
> Use an updated version of both the client and the server

Running the server off the `develop` branch fails. This is not an issue with an outdated server.

**Comment by danpantry** [comment]
Would it be worth having a version check handshake to prevent this BTW? Notwithstanding @Jacwah's comment

**Comment by Zomis** [comment]
>  I have come to the conclusion that it was never possible for the HTML-Client to connect to any server other than a local one. 

I believe that is because the other servers are outdated.

> Running the server off the develop branch fails. This is not an issue with an outdated server.

It is, actually. The changes to fix this issue seems to have been done on the `rules` branch, which has not been merged into `develop` [as far as I can see](https://github.com/Cardshifter/Cardshifter/network).

**Comment by jacwah** [comment]
@Zomis So the snapshots are not based off the `develop` branch? If that's the case, it's the reason for this confusion.

**Comment by Zomis** [comment]
The snapshots are based on whatever commit I run `gradlew snapshot` from.
