### ISSUE TITLE
NPE when performing action

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#419]
This happened during the AI's turn in a Mythos game. From reading the log, it looks like the server thought I was trying to play a card that belonged to the AI, though I'm not completely sure.

[Server log](https://gist.github.com/jacwah/dd8046ec2f572e802f5f)

**Comment by jacwah** [comment]
#### The error

```
[2015-10-09 19:23:27,697] ERROR   AISystem [ai-thread-0] (         AISystem.java: 93) - Entity #111 Error performing Play for entity Entity #120
java.lang.RuntimeException: Error performing action Play for entity Entity #120
[...]
Caused by: java.lang.NullPointerException
```

#### Entity 111

The AI.

```
[2015-10-09 19:22:50,324] INFO ClientWebSocket [WebSocketWorker-12] ( ClientWebSocket.java: 73) - Sending to client: Player Info: AI Fighter - {MAX_HEALTH=30, MANA=0, MAX_MANA=0, HEALTH=30} - {"command":"player","name":"AI Fighter","properties":{"MAX_HEALTH":30,"MANA":0,"MAX_MANA":0,"HEALTH":30},"index":0,"id":111}
```

#### Entity 120

An Undead.

```
[2015-10-09 19:22:50,377] INFO Log4jAdapter [WebSocketWorker-12] ( Log4jAdapter.java: 16) - Send to AI Fighter: CardInfo: 120 in zone 113 - {MAX_HEALTH=5, MANA_UPKEEP=5, imagePath=mythos/common/undead.jpg, SICKNESS=1, effect=Give creatures of type Common owned by opponent on Battlefield -1 HEALTH
```

#### Entity 120 played

This is were the card is played originally.

```
[2015-10-09 19:23:27,671]  INFO   AISystem [ai-thread-0] (         AISystem.java: 80) - Entity #111 performs Play for entity Entity #120
[2015-10-09 19:23:27,673]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to AI Fighter: UseAbilityMessage [id=120, action=Play, gameId=1, performer=111, targets=[]]
[2015-10-09 19:23:27,673]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to jacwah: UseAbilityMessage [id=120, action=Play, gameId=1, performer=111, targets=[]]
[2015-10-09 19:23:27,673]  INFO ClientWebSocket [ai-thread-0] (  ClientWebSocket.java: 73) - Sending to client: UseAbilityMessage [id=120, action=Play, gameId=1, performer=111, targets=[]] - {"command":"use","requestId":0,"id":120,"action":"Play","gameId":1,"targets":[],"performer":111}
[2015-10-09 19:23:27,673]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to AI Fighter: UpdateMessage [id=111, key=MANA, value=0]
[2015-10-09 19:23:27,674]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to jacwah: UpdateMessage [id=111, key=MANA, value=0]
[2015-10-09 19:23:27,674]  INFO ClientWebSocket [ai-thread-0] (  ClientWebSocket.java: 73) - Sending to client: UpdateMessage [id=111, key=MANA, value=0] - {"command":"update","id":111,"key":"MANA","value":0}
[2015-10-09 19:23:27,681]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to AI Fighter: ZoneChangeMessage [entity=120, sourceZone=113, destinationZone=114]
[2015-10-09 19:23:27,681]  INFO Log4jAdapter [ai-thread-0] (     Log4jAdapter.java: 16) - Send to jacwah: ZoneChangeMessage [entity=120, sourceZone=113, destinationZone=114]
```

### Conclusion

The AI tries to play the same card twice, resulting in a null pointer error.

**Comment by jacwah** [comment]
After some testing I realized that as soon as the AI plays Undead this error occurs. I don't know whether it's an issue with the model or AI yet.

[Another log](https://gist.github.com/jacwah/3832730368e2909e0ab5)

**Comment by Zomis** [comment]
Some more details about the NPE:

    Caused by: java.lang.NullPointerException
	at com.sun.proxy.$Proxy22.test(Unknown Source)
	at net.zomis.cardshifter.ecs.effects.TargetFilter.lambda$and$52(TargetFilter.java:11)
	at net.zomis.cardshifter.ecs.effects.TargetFilter.lambda$and$52(TargetFilter.java:11)
	at net.zomis.cardshifter.ecs.effects.TargetFilter.lambda$and$52(TargetFilter.java:11)
	at com.cardshifter.modapi.resources.EntityModifier.appliesTo(EntityModifier.java:31)
	at com.cardshifter.modapi.resources.ResourceModifierComponent.getResource(ResourceModifierComponent.java:33)
	at com.cardshifter.modapi.resources.ECSResourceData.get(ECSResourceData.java:30)
	at com.cardshifter.modapi.resources.ResourceRecountSystem.lambda$null$57(ResourceRecountSystem.java:36)
